# Generated by Django 5.2.6 on 2025-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('orders_per_day', 'Orders Per Day'), ('error_rate', 'Error Rate'), ('refunds_per_day', 'Refunds Per Day'), ('payment_success_rate', 'Payment Success Rate'), ('avg_response_time', 'Average Response Time'), ('circuit_breaker_state', 'Circuit Breaker State'), ('stock_conflicts', 'Stock Conflicts'), ('throttled_requests', 'Throttled Requests')], max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_type', '-recorded_at'], name='retail_metr_metric__f6d35c_idx'), models.Index(fields=['-recorded_at'], name='retail_metr_recorde_064b11_idx')],
            },
        ),
    ]
