# Generated by Django 5.2.6 on 2025-10-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_feeds', '0001_initial'),
        ('products', '0002_product_flash_sale_end_product_flash_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_flas_154eda_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_flash_sale',
            new_name='flash_sale_enabled',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='flash_sale_end',
            new_name='flash_sale_ends_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='flash_sale_start',
            new_name='flash_sale_starts_at',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['flash_sale_enabled'], name='products_pr_flash_s_da6530_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('flash_sale_enabled', False), models.Q(('flash_sale_enabled', True), ('flash_sale_ends_at__isnull', False), ('flash_sale_price__isnull', False), ('flash_sale_starts_at__isnull', False), ('flash_sale_starts_at__lt', models.F('flash_sale_ends_at'))), _connector='OR')), name='flash_sale_time_order'),
        ),
    ]
