# Generated by Django 5.2.6 on 2025-11-12 18:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_order_payment_sale_rename_order_sale_saleitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('received', 'Received'), ('refunded', 'Refunded'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('reason', models.CharField(choices=[('defective', 'Defective/Damaged'), ('wrong_item', 'Wrong Item Received'), ('not_as_described', 'Not as Described'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], max_length=50)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Customer notes or staff inspection notes')),
                ('tracking_number', models.CharField(blank=True, help_text='Return shipment tracking number', max_length=100, null=True)),
                ('restocking_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Restocking fee amount', max_digits=10)),
                ('shipping_refund', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping refund amount', max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmas', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmas', to='orders.sale')),
            ],
            options={
                'verbose_name': 'RMA',
                'verbose_name_plural': 'RMAs',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_events', to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='returns.rma')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RMAItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.PositiveIntegerField(help_text='Quantity customer requested to return')),
                ('approved_quantity', models.PositiveIntegerField(blank=True, help_text='Quantity approved for return (set by staff)', null=True)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.rma')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rma_items', to='orders.saleitem')),
            ],
            options={
                'unique_together': {('rma', 'sale_item')},
            },
        ),
    ]
