# Generated by Django 5.2.6 on 2025-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='resolution',
            field=models.CharField(blank=True, choices=[('repair', 'Repair'), ('replacement', 'Replacement'), ('refund', 'Refund')], help_text="Customer's choice: Repair, Replacement, or Refund", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rma',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('validated', 'Validated'), ('request_cancelled', 'Request Cancelled'), ('in_transit', 'In Transit'), ('received', 'Received'), ('under_inspection', 'Under Inspection'), ('approved', 'Approved'), ('refunded', 'Refunded'), ('closed', 'Closed')], default='requested', max_length=20),
        ),
    ]
