# Generated by Django 5.2.6 on 2025-11-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_alter_rma_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rma',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('validated', 'Validated'), ('request_cancelled', 'Request Cancelled'), ('in_transit', 'In Transit'), ('received', 'Received'), ('under_inspection', 'Under Inspection'), ('approved', 'Approved'), ('repaired', 'Repaired'), ('replaced', 'Replaced'), ('refunded', 'Refunded'), ('declined', 'Declined'), ('closed', 'Closed')], default='requested', max_length=20),
        ),
    ]
