# Generated by Django 5.2.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('returns', '0004_alter_rma_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMANotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='RMA status that triggered this notification', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='returns.rma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rmanotification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='returns_rman_user_id_12345_idx'),
        ),
    ]

