# Generated by Django 5.2.6 on 2025-11-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0005_rmanotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='rmanotification',
            new_name='returns_rma_user_id_cff6eb_idx',
            old_name='returns_rman_user_id_12345_idx',
        ),
    ]
